server:
  port: 8001
spring:
  application:
    name: service-hellow
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90